spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  profiles:
    active:
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: production
