version: "3.8"

services:
  db:
    image: vt-db
    restart: always
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vehicle-tracker
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - network

volumes:
  pgdata:
    driver: local

networks:
  network:
    driver: bridge
